build:
  image: registry.aliyuncs.com/xiaolu-img/xiaolusys-base:f8c653222e8a9d9d0cbe301bec4446957500e235
  environment:
    - TARGET=staging
    - MYSQL_AUTH=$$MYSQL_AUTH
    - REDIS_AUTH=$$REDIS_AUTH2
  volumes:
    - /var/lib/drone/data:/data
  commands:
    - mkdir -p /data/log/django
    - python manage.py test -t . --keepdb --exclude-tag=B --exclude-tag=C
    - python manage.py migrate --noinput
  when:
    branch: [staging, alpha, warden]
publish:
  docker:
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    registry: registry.aliyuncs.com
    repo: ndpuz-img/ndpuzsys
    tag: latest
    file: Dockerfile
    mirror: https://kpm1lqaf.mirror.aliyuncs.com
    when:
      branch: alpha
  docker:
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    registry: registry.aliyuncs.com
    repo: ndpuz-img/ndpuzsys
    tag: django18
    file: Dockerfile
    mirror: https://kpm1lqaf.mirror.aliyuncs.com
    when:
      branch: django18
  docker:
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    registry: registry.aliyuncs.com
    repo: ndpuz-img/ndpuzsys
    tag: warden
    file: Dockerfile
    mirror: https://kpm1lqaf.mirror.aliyuncs.com
    when:
      branch: warden



