build:
  image: registry.aliyuncs.com/xiaolu-img/xiaolusys-base:8d2dc9f8a7a279f200804447632d7a58c2b9bacb
  environment:
    - TARGET=staging
    - REDIS_AUTH=$$REDIS_AUTH
  commands:
    - mkdir -p /data/log/django
    - cd shopmanager;python manage.py migrate --noinput
    - python manage.py test -t . --keepdb
  when:
    branch: [staging, alpha, warden]
publish:
  docker:
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    registry: registry.aliyuncs.com
    repo: xiaolu-img/xiaolusys
    tag: latest
    file: Dockerfile
    mirror: https://n5fb0zgg.mirror.aliyuncs.com
    when:
      branch: alpha
  docker:
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    registry: registry.aliyuncs.com
    repo: xiaolu-img/xiaolusys
    tag: django18
    file: Dockerfile
    mirror: https://n5fb0zgg.mirror.aliyuncs.com
    when:
      branch: django18
  docker:
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    registry: registry.aliyuncs.com
    repo: xiaolu-img/xiaolusys
    tag: warden
    file: Dockerfile
    mirror: https://n5fb0zgg.mirror.aliyuncs.com
    when:
      branch: warden
deploy:
  ssh:
    host: staging.xiaolumm.com
    user: root
    when:
      branch: admin
    commands:
      - docker pull registry.aliyuncs.com/xiaolu-img/xiaolusys:latest      
      - docker rm -f gunicorn 
      - docker run --name=gunicorn --restart=always
        -e TARGET=production -e INSTANCE=admin -e MYSQL_AUTH=$$MYSQL_AUTH -e REDIS_AUTH=$$REDIS_AUTH
        --volumes-from=static -d -p `ifconfig eth0 | awk '/inet addr/{print substr($2,6)}'`:9000:9000 -e BLUEWARE_CONFIG_FILE=blueware.ini
        registry.aliyuncs.com/xiaolu-img/xiaolusys:latest gunicorn -k gevent -c taobao_gunicorn_conf.py -w 4 shopmanager.wsgi
      - docker rm -f celery-flower
      - docker run --name=celery-flower --restart=always -e TARGET=production -e MYSQL_AUTH=$$MYSQL_AUTH -e REDIS_AUTH=$$REDIS_AUTH
        -d -p `ifconfig eth0 | awk '/inet addr/{print substr($2,6)}'`:5555:5555 -e C_FORCE_ROOT=1
        registry.aliyuncs.com/xiaolu-img/xiaolusys:latest celery flower -A shopmanager --loglevel=ERROR
      - docker rm -f celerybeat
      - docker run --name=celerybeat --restart=always -e TARGET=production -e MYSQL_AUTH=$$MYSQL_AUTH -e REDIS_AUTH=$$REDIS_AUTH
        -d registry.aliyuncs.com/xiaolu-img/xiaolusys:latest python manage.py celery beat --loglevel=ERROR
  ssh:
    host: staging.xiaolumm.com
    user: root
    when:
      branch: [admin, celery]
    commands:
      - docker pull registry.aliyuncs.com/xiaolu-img/xiaolusys:latest
      - docker rm -f celery
      - docker run --name=celery --restart=always --memory=2048m --cpu-period=100000 --cpu-quota=100000 -e TARGET=production -e MYSQL_AUTH=$$MYSQL_AUTH -e REDIS_AUTH=$$REDIS_AUTH
        --volumes-from=static -d -e BLUEWARE_CONFIG_FILE=blueware.ini -e C_FORCE_ROOT=1 registry.aliyuncs.com/xiaolu-img/xiaolusys:latest
        blueware-admin run-program celery worker -c 4 -A shopmanager --time-limit=5400
        --loglevel=ERROR -Q apis,default,peroid,async,notify,logistics,dinghuo
  ssh:
    host: staging.xiaolumm.com
    user: root
    when:
      branch: alpha
    commands:
      - docker pull registry.aliyuncs.com/xiaolu-img/xiaolusys:latest
      - docker rm -f gunicorn-staging
      - docker run --name=gunicorn-staging --restart=always
        -e INSTANCE=mall -e TARGET=staging -e REDIS_AUTH=$$REDIS_AUTH
        --volumes-from=static -d -p `ifconfig eth0 | awk '/inet addr/{print substr($2,6)}'`:9001:9000 -e
        BLUEWARE_CONFIG_FILE=blueware.ini registry.aliyuncs.com/xiaolu-img/xiaolusys:latest
        blueware-admin run-program gunicorn -k gevent -w 1 -c staging_gunicorn_conf.py shopmanager.wsgi
  ssh:
    host: staging.xiaolumm.com
    user: root
    when:
      branch: django18
    commands:
      - docker pull registry.aliyuncs.com/xiaolu-img/xiaolusys:django18
      - docker rm -f gunicorn-django18
      - docker run --name=gunicorn-django18 --restart=always
        -e INSTANCE=mall -e TARGET=django18 -e MYSQL_AUTH=$$MYSQL_AUTH -e REDIS_AUTH=$$REDIS_AUTH
        --volumes-from=static -d -p `ifconfig eth0 | awk '/inet addr/{print substr($2,6)}'`:9002:9000
        -e BLUEWARE_CONFIG_FILE=blueware.ini registry.aliyuncs.com/xiaolu-img/xiaolusys:django18
        blueware-admin run-program gunicorn -k gevent -w 1 -c staging_gunicorn_conf.py shopmanager.wsgi
  ssh:
    host: staging.xiaolumm.com
    user: root
    when:
      branch: warden
    commands:
      - docker pull registry.aliyuncs.com/xiaolu-img/xiaolusys:warden
      - docker rm -f gunicorn-warden
      - docker run --name=gunicorn-warden --restart=always
        -e INSTANCE=mall -e TARGET=staging -e REDIS_AUTH=$$REDIS_AUTH
        --volumes-from=static -d -p `ifconfig eth0 | awk '/inet addr/{print substr($2,6)}'`:9009:9000
        -e BLUEWARE_CONFIG_FILE=blueware.ini registry.aliyuncs.com/xiaolu-img/xiaolusys:warden
        blueware-admin run-program gunicorn -k gevent -w 1 -c staging_gunicorn_conf.py shopmanager.wsgi
  ssh:
    host:
      - sale.xiaolumm.com
      - sale4.xiaolumm.com
      - sale8.xiaolumm.com
    user: root
    when:
      branch: master
    commands:
      - docker pull registry.aliyuncs.com/xiaolu-img/xiaolusys:latest
      - docker rm -f gunicorn
      - docker run --name=gunicorn --restart=always
        -e INSTANCE=mall -e TARGET=production -e MYSQL_AUTH=$$MYSQL_AUTH -e REDIS_AUTH=$$REDIS_AUTH
        --volumes-from=static -d -p `ifconfig eth0 | awk '/inet addr/{print substr($2,6)}'`:9000:9000
        -e BLUEWARE_CONFIG_FILE=blueware.ini registry.aliyuncs.com/xiaolu-img/xiaolusys:latest
        blueware-admin run-program gunicorn -k gevent -c taobao_gunicorn_conf.py shopmanager.wsgi
  ssh:
    host:
      - sale8.xiaolumm.com
    user: root
    when:
      branch: master
    commands:
      - docker pull registry.aliyuncs.com/xiaolu-img/xiaolusys:latest
      - docker rm -f gunicorn-prometheus
      - docker run --name=gunicorn-prometheus --restart=always
        -e INSTANCE=mall -e TARGET=prometheus -e MYSQL_AUTH=$$MYSQL_AUTH -e REDIS_AUTH=$$REDIS_AUTH
        --volumes-from=static -d -p `ifconfig eth0 | awk '/inet addr/{print substr($2,6)}'`:9004:9000
        -e BLUEWARE_CONFIG_FILE=blueware.ini registry.aliyuncs.com/xiaolu-img/xiaolusys:latest
        blueware-admin run-program gunicorn -k gevent -w 1 -c taobao_gunicorn_conf.py shopmanager.wsgi
  ssh:
    host:
      - sale.xiaolumm.com
      - sale4.xiaolumm.com
    user: root
    when:
      branch: [master, celery]
    commands:
      - docker pull registry.aliyuncs.com/xiaolu-img/xiaolusys:latest
      - docker rm -f celery
      - docker run --name=celery --restart=always -e TARGET=production -e MYSQL_AUTH=$$MYSQL_AUTH -e REDIS_AUTH=$$REDIS_AUTH
        --volumes-from=static -d -e BLUEWARE_CONFIG_FILE=blueware.ini -e C_FORCE_ROOT=1 registry.aliyuncs.com/xiaolu-img/xiaolusys:latest
        blueware-admin run-program celery worker -c 4 -A shopmanager --loglevel=ERROR --time-limit=5400
        -Q notify,default,frency,coupon,activevalue,mama,mamafortune,relationship,carryrecord,skustats,statistics,logistics,carrytotal,integral,dinghuo
  ssh:
    host:
      - sale2.xiaolumm.com
      - sale9.xiaolumm.com
    user: root
    when:
      branch: [master, celery]
    commands:
      - docker pull registry.aliyuncs.com/xiaolu-img/xiaolusys:latest
      - docker rm -f celery1
      - docker run --name=celery1 --restart=always -d
        -e INSTANCE=celery-gevent -e TARGET=production -e MYSQL_AUTH=$$MYSQL_AUTH -e REDIS_AUTH=$$REDIS_AUTH
        --volumes-from=static -e C_FORCE_ROOT=1 -e BLUEWARE_CONFIG_FILE=blueware.ini -e C_FORCE_ROOT=1
        registry.aliyuncs.com/xiaolu-img/xiaolusys:latest blueware-admin run-program
        celery worker -P gevent -A shopmanager --loglevel=ERROR -c 300 --time-limit=300
        -Q notify,frency,mama,coupon,activevalue,mamafortune,relationship,carryrecord,logistics,weixin
      - docker rm -f celery2
      - docker run --name=celery2 --restart=always -d
        -e INSTANCE=celery-gevent -e TARGET=production -e MYSQL_AUTH=$$MYSQL_AUTH -e REDIS_AUTH=$$REDIS_AUTH
        --volumes-from=static -e C_FORCE_ROOT=1 -e BLUEWARE_CONFIG_FILE=blueware.ini -e C_FORCE_ROOT=1
        registry.aliyuncs.com/xiaolu-img/xiaolusys:latest blueware-admin run-program
        celery worker -P gevent -A shopmanager --loglevel=ERROR -c 300 --time-limit=300
        -Q notify,frency,mama,coupon,activevalue,mamafortune,relationship,carryrecord,logistics,qrcode
      - docker rm -f celery3
      - docker run --name=celery3 --restart=always -d
        -e INSTANCE=celery-gevent -e TARGET=production -e MYSQL_AUTH=$$MYSQL_AUTH -e REDIS_AUTH=$$REDIS_AUTH
        --volumes-from=static -e C_FORCE_ROOT=1 -e BLUEWARE_CONFIG_FILE=blueware.ini -e C_FORCE_ROOT=1
        registry.aliyuncs.com/xiaolu-img/xiaolusys:latest blueware-admin run-program
        celery worker -P gevent -A shopmanager --loglevel=ERROR -c 300 --time-limit=300
        -Q notify,frency,mama,coupon,activevalue,mamafortune,relationship,carryrecord,logistics,qrcode
      - docker rm -f celery4
      - docker run --name=celery4 --restart=always -d
        -e INSTANCE=celery-gevent -e TARGET=production -e MYSQL_AUTH=$$MYSQL_AUTH -e REDIS_AUTH=$$REDIS_AUTH
        --volumes-from=static -e C_FORCE_ROOT=1 -e BLUEWARE_CONFIG_FILE=blueware.ini -e C_FORCE_ROOT=1
        registry.aliyuncs.com/xiaolu-img/xiaolusys:latest blueware-admin run-program
        celery worker -P gevent -A shopmanager --loglevel=ERROR -c 300 --time-limit=300
        -Q notify,frency,mama,coupon,activevalue,mamafortune,relationship,carryrecord,logistics,qrcode
  ssh:
    host:
      - sale9.xiaolumm.com
    user: root
    when:
      branch: [master, celery]
    commands:
      - docker pull registry.aliyuncs.com/xiaolu-img/xiaolusys:latest
      - docker rm -f celery
      - docker run --name=celery --restart=always -d
        -e TARGET=production -e MYSQL_AUTH=$$MYSQL_AUTH -e REDIS_AUTH=$$REDIS_AUTH
        --volumes-from=static -e C_FORCE_ROOT=1 -e BLUEWARE_CONFIG_FILE=blueware.ini -e C_FORCE_ROOT=1
        registry.aliyuncs.com/xiaolu-img/xiaolusys:latest blueware-admin run-program
        celery worker -A shopmanager --loglevel=ERROR -c 48 --time-limit=5400
        -Q notify,default,peroid,frency,coupon,activevalue,mama,mamafortune,relationship,carryrecord,skustats,statistics,logistics,carrytotal,integral,dinghuo



