build:
  image: registry.aliyuncs.com/xiaolu-img/xiaolusys-base:a3464951565161bb9831e48e6e7a1b1fa5476c64
  environment:
    - TARGET=staging
    - REDIS_AUTH=$$REDIS_AUTH2
  volumes:
    - /var/lib/drone/data:/data
  commands:
    - mkdir -p /data/log/django
    - python manage.py test -t . --keepdb  --exclude-tag=B --exclude-tag=C
    - python manage.py migrate --noinput
  when:
    branch: [staging, alpha, warden]
publish:
  docker:
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    registry: registry.aliyuncs.com
    repo: xiaolu-img/xiaolusys
    tag: latest
    file: Dockerfile
    mirror: https://n5fb0zgg.mirror.aliyuncs.com
    when:
      branch: alpha
  docker:
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    registry: registry.aliyuncs.com
    repo: xiaolu-img/xiaolusys
    tag: django18
    file: Dockerfile
    mirror: https://n5fb0zgg.mirror.aliyuncs.com
    when:
      branch: django18
  docker:
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    registry: registry.aliyuncs.com
    repo: xiaolu-img/xiaolusys
    tag: warden
    file: Dockerfile
    mirror: https://n5fb0zgg.mirror.aliyuncs.com
    when:
      branch: warden
deploy:
  ssh:
    host: sale2.xiaolumm.com
    user: root
    when:
      branch: admin
    commands:
      - docker pull registry.aliyuncs.com/xiaolu-img/xiaolusys:latest
      - docker rm -f gunicorn
      - docker run --name=gunicorn --restart=always --log-opt max-file=1 --log-opt max-size=1m --memory=6144m
        -e TARGET=production -e INSTANCE=admin -e MYSQL_AUTH=$$MYSQL_AUTH -e REDIS_AUTH=$$REDIS_AUTH2
        -v /var/data:/data -d -p `ifconfig eth0 | awk '/inet addr/{print substr($2,6)}'`:9000:9000
        registry.aliyuncs.com/xiaolu-img/xiaolusys:latest gunicorn -k gevent -c gunicorn_config.py -w 4 shopmanager.wsgi
  ssh:
    host: sale2.xiaolumm.com
    user: root
    when:
      branch: [admin, celery]
    commands:
      - docker pull registry.aliyuncs.com/xiaolu-img/xiaolusys:latest
      - docker rm -f celery
      - docker run --name=celery --restart=always --log-opt max-file=1 --log-opt max-size=1m --memory=2048m
        --cpu-period=100000 --cpu-quota=100000 -e TARGET=production -e MYSQL_AUTH=$$MYSQL_AUTH -e REDIS_AUTH=$$REDIS_AUTH2
        -v /var/data:/data -d  -e C_FORCE_ROOT=1 registry.aliyuncs.com/xiaolu-img/xiaolusys:latest
        celery worker -c 2 -A shopmanager --time-limit=5400
        --loglevel=info -Q apis,default,async,notify,dinghuo,xiaolupay
  ssh:
    host: sale2.xiaolumm.com
    user: root
    when:
      branch: alpha
    commands:
      - docker pull registry.aliyuncs.com/xiaolu-img/xiaolusys:latest
      - docker rm -f gunicorn-staging
      - docker run --name=gunicorn-staging --restart=always --log-opt max-file=1 --log-opt max-size=1m
        -e INSTANCE=mall -e TARGET=staging -e REDIS_AUTH=$$REDIS_AUTH2
        -v /var/data:/data -d -p `ifconfig eth0 | awk '/inet addr/{print substr($2,6)}'`:9001:9000
        registry.aliyuncs.com/xiaolu-img/xiaolusys:latest
        gunicorn -k gevent -w 1 -c gunicorn_config.py shopmanager.wsgi
  ssh:
    host: sale2.xiaolumm.com
    user: root
    when:
      branch: django18
    commands:
      - docker pull registry.aliyuncs.com/xiaolu-img/xiaolusys:django18
      - docker rm -f gunicorn-django18
      - docker run --name=gunicorn-django18 --restart=always --log-opt max-file=1 --log-opt max-size=1m
        -e INSTANCE=mall -e TARGET=django18 -e MYSQL_AUTH=$$MYSQL_AUTH -e REDIS_AUTH=$$REDIS_AUTH2
        -v /var/data:/data -d -p `ifconfig eth0 | awk '/inet addr/{print substr($2,6)}'`:9002:9000
        registry.aliyuncs.com/xiaolu-img/xiaolusys:django18
        gunicorn -k gevent -w 1 -c gunicorn_config.py shopmanager.wsgi
  ssh:
    host: sale2.xiaolumm.com
    user: root
    when:
      branch: flower
    commands:
      - docker pull registry.aliyuncs.com/xiaolu-img/xiaolusys:latest
      - docker rm -f celery-flower
      - docker run --name=celery-flower --restart=always -e TARGET=production --memory=1024m
        -e MYSQL_AUTH=$$MYSQL_AUTH -e REDIS_AUTH=$$REDIS_AUTH2 -e FLOWER_BASIC_AUTH=xiaolu:2016xiaoluyear
        -d -p `ifconfig eth0 | awk '/inet addr/{print substr($2,6)}'`:5555:5555
        -v /var/data:/data  -e C_FORCE_ROOT=1 registry.aliyuncs.com/xiaolu-img/xiaolusys:latest
        flower -A shopmanager --log_file_max_size=1073741824 --conf=shopmanager/task_settings.py
  ssh:
    host:
      - sale8.xiaolumm.com
    user: root
    when:
      branch: [master, prometheus]
    commands:
      - docker pull registry.aliyuncs.com/xiaolu-img/xiaolusys:latest
      - docker rm -f gunicorn
      - docker run --name=gunicorn --restart=always --log-opt max-file=1 --log-opt max-size=1m --memory=6144m
        -e INSTANCE=mall -e TARGET=production -e MYSQL_AUTH=$$MYSQL_AUTH -e REDIS_AUTH=$$REDIS_AUTH2
        -v /var/data:/data -d -p `ifconfig eth0 | awk '/inet addr/{print substr($2,6)}'`:9000:9000
        registry.aliyuncs.com/xiaolu-img/xiaolusys:latest
        gunicorn -k gevent -w 10 -c gunicorn_config.py shopmanager.wsgi
      - docker rm -f gunicorn-prometheus
      - docker run --name=gunicorn-prometheus --restart=always --log-opt max-file=1 --log-opt max-size=1m --memory=600m
        -e INSTANCE=mall -e TARGET=prometheus -e MYSQL_AUTH=$$MYSQL_AUTH -e REDIS_AUTH=$$REDIS_AUTH2
        -v /var/data:/data -d -p `ifconfig eth0 | awk '/inet addr/{print substr($2,6)}'`:9004:9000
        registry.aliyuncs.com/xiaolu-img/xiaolusys:latest
        gunicorn -k gevent -w 1 -c gunicorn_config.py shopmanager.wsgi
  ssh:
    host:
      - sale8.xiaolumm.com
    user: root
    when:
      branch: [master, celery]
    commands:
      - docker pull registry.aliyuncs.com/xiaolu-img/xiaolusys:latest
      - docker rm -f celery1
      - docker run  --name=celery1 --restart=always -d --log-opt max-file=1 --log-opt max-size=1m --memory=1024m
        -e INSTANCE=celery-gevent -e TARGET=production -e MYSQL_AUTH=$$MYSQL_AUTH -e REDIS_AUTH=$$REDIS_AUTH2
        -v /var/data:/data -e C_FORCE_ROOT=1 registry.aliyuncs.com/xiaolu-img/xiaolusys:latest
        celery worker -P gevent -A shopmanager --loglevel=ERROR -c 200 --time-limit=1800
        -Q apis,notify,frency,mama,coupon,activevalue,mamafortune,relationship,carryrecord,logistics,weixin,qrcode,xiaolupay
      - docker rm -f celery2
      - docker run --name=celery2 --restart=always -d --log-opt max-file=1 --log-opt max-size=1m --memory=1024m
        -e INSTANCE=celery-gevent -e TARGET=production -e MYSQL_AUTH=$$MYSQL_AUTH -e REDIS_AUTH=$$REDIS_AUTH2
        -v /var/data:/data -e C_FORCE_ROOT=1 registry.aliyuncs.com/xiaolu-img/xiaolusys:latest
        celery worker -P gevent -A shopmanager --loglevel=ERROR -c 200 --time-limit=1800
        -Q apis,notify,frency,mama,coupon,activevalue,mamafortune,relationship,carryrecord,logistics,qrcode,weixin



